Creating activity-content-editor to align with pre-existing activity editors
BrightspaceHypermediaComponents/activities pull request #1113
Opened 2020-09-17 15:17 UTC by imcdonald-d2l

In summary, this PR starts the work to align our face create experience with the approach utilized by assignments. It adds the name field to the UI and a MobX store to keep track of this value and content activities.

Specifically the work done in this PR:
- Created `<d2l-activity-content-editor>` this is the parent component/editor that all future components will be added to. It contains the `<d2l-activity-editor>` and template component which we fill with our custom components for the primary, secondary and footer slots.
- Created `d2l-activity-content-editor-detail`. This is where the title input field exists. Mobx hooks have been added here to get  the name from state when rendering and updating the state with any updates made to this field. 
- Created `d2l-activity-content-editor-footer`. This is where the save/cancel buttons exist. Right now they don't function but I have added the UI components for future tweaking when we properly setup the save/cancel functionality.
Created a MobX store with `content-store.js` and `content.js `. These two files allow us to load the content activity items into the store while accessing and editing the `title` property. 

This is what the UI looks like right now:
![title](https://user-images.githubusercontent.com/64804046/93490873-07c17f00-f8d7-11ea-85f3-683d89678aee.png)

**Note:** you won't be able to test this just yet as back end requires a bit more work. Putting this PR up early so you can ask any questions you may have.

2020-09-17 15:27 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +			this.clearError(errorProperty);
`this.setError` and `this.clearError` come from `ErrorHandlingMixin`

2020-09-17 15:34 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +	}
These two functions will be used by `ActivityEditorContainerMixin` when we get around to implementing the save/cancel functionality

2020-09-17 15:34 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +			super._fetch(() => store.fetchContentActivity(this.href, this.token));
this gets the content activity and adds it to the store

2020-09-17 15:36 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/state/content.js
> +		this.title = entity.title();
`title()` function comes from the defined function in siren-sdk repo [here](https://github.com/BrightspaceHypermediaComponents/siren-sdk/blob/master/src/activities/content/ContentEntity.js#L10).

2020-09-17 16:09 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +import { ErrorHandlingMixin } from '../error-handling-mixin.js';
small nit that we could get in the habit of doing: it will look better if we group the imports with all of our absolute (dependency) imports above all the relative imports. It will help give an idea of what each file is using at a glance.

2020-09-17 16:12 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +	_getTitleTooltip() {
I might be thinking in React, but should this function be named `renderTitleTooltip` ?

2020-09-17 16:21 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +		const emptyNameErrorLangterm = 'content.emptyNameField';
nit: redeclaring these on every save feels a little redundant, maybe we can have them defined somewhere else or do them inline?

2020-09-17 16:26 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-footer.js
> +				flex-direction: row-reverse;
any reason to use `row-reverse` and not just row and have the elements in the right order?

2020-09-17 16:31 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +			widthType: { type: String, attribute: 'width-type' }
can you explain what's going on with this and why it's needed?

2020-09-17 16:36 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +			widthType: { type: String, attribute: 'width-type' }
Like why it's a property

2020-09-17 16:36 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +		this.type = 'content';
nit: can this just be inlined? seems to only be used once

2020-09-17 16:37 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +		super.updated(changedProperties);
what does the parent `updated` do and does it need to be inside your check below?

2020-09-17 16:47 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +import { ErrorHandlingMixin } from '../error-handling-mixin.js';
I think we may be limited to ordering imports alphabetically in the activities repo. Every file I'm seeing has them ordered that way 😞

2020-09-17 16:49 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-footer.js
> +				flex-direction: row-reverse;
That's a good point. Just copied the styles from the `assignment-editor-footer` but will clean these up so it is more logical.

2020-09-17 16:54 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +import { ErrorHandlingMixin } from '../error-handling-mixin.js';
ah, that's fair. we dont need to stray from the existing rules

2020-09-17 16:54 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +	_getTitleTooltip() {
Yeah, would probably make more sense to be named that way. 👍

2020-09-17 16:55 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +		const emptyNameErrorLangterm = 'content.emptyNameField';
That's a good point, inline would work nicely!

2020-09-17 16:55 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +				height: calc(100% - 20px);
This kinda stuff makes me nervous, LX had a lot of these calcs with seemingly "random" pixel offsets. I would suggest finding a different way or at least putting these into CSS vars

2020-09-17 16:55 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +				height: calc(100% - 20px);
Like if the 20px in the primary slot div changes and this doesn't, things are gonna look weird and it might be hard to spot why

2020-09-17 17:02 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +			:host([dir="rtl"]) d2l-icon {
kinda sucks that we have to duplicate & inverse the css for rtl stuff... I think Lessons used some library that handled that for us, I wonder if this repo has anything like that? is this what other files are doing?

2020-09-17 17:14 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +				height: calc(100% - 20px);
Good point, it's a result of the `padding` property right below this one. Will swap out value for a variable 👍

2020-09-17 17:16 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +			:host([dir="rtl"]) d2l-icon {
This was a copy/paste from `assignment-editor-detail` component. Looks like some files are taking a manual approach for tweaking `rtl` stuff. Not seeing any immediate libraries being used.

2020-09-17 17:25 UTC, dbatiste commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +			:host([dir="rtl"]) d2l-icon {
👍 This is the standard approach that needs to be applied.  Typically, the RTL assignments are pretty trivial, but eventually the browsers will all support CSS properties that are agnostic to direction. ex. start/end vs left/right.

2020-09-17 17:44 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +		super.updated(changedProperties);
good catch, the `super.updated()` isn't actually needed here. `super` is referencing  `ActivityEditorMixin` in this file. Debugging led me to find that `super.updated()` which goes to [this line](https://github.com/BrightspaceHypermediaComponents/activities/blob/master/components/d2l-activity-editor/mixins/d2l-activity-editor-mixin.js#L64) would execute the same thing as the block below but doesn't execute properly. Since `store` ends up being `undefined`.

2020-09-17 17:53 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +			widthType: { type: String, attribute: 'width-type' }
this property is used on line 84 within this file and set on the BE [here](https://search.d2l.dev/xref/lms/le/content/D2L.LE.Content/Web/Desktop/Views/Lessons/ContentCreationViewFactory.cs?r=0ccdf8d6#41). It sets the width type of the template component. Arguably it will never change from `fullscreen` but doesn't hurt to have the ability to change that in the future.

2020-09-17 18:12 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +				padding: 20px;
is this supposed to be `2 * --d2l-secondary-padding` ?

2020-09-17 18:14 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
> +				padding: 20px;
I can add a new variable for primary padding and set the height accordingly 👍

2020-09-17 18:15 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/state/content-store.js
> +export const { _contents: contents } = shared;
is this used anywhere? seems like only the `shared` is being used. i might be wrong though

2020-09-17 18:26 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/state/content-store.js
> +export const { _contents: contents } = shared;
haha nothing gets passed you! No, it is not being used right now. I removed it. Good catch 👍

2020-09-18 14:59 UTC, ChrisKraljevicD2L commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +				<label class="d2l-label-text" for="content-title">${this.localize('content.name')}*</label>
Why is there an asterix after `${this.localize('content.name')}`?

2020-09-18 14:59 UTC, ChrisKraljevicD2L commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +					?showing="${this._titleError}">
Does `_titleError` work as a falsy statement? No `!!` needed?

2020-09-18 14:59 UTC, ChrisKraljevicD2L commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +				timeOut.after(500),
I'm pretty consistent with being nitty about magic numbers and this is no different :P Where does this 500ms timeout come from?

2020-09-18 15:06 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +				<label class="d2l-label-text" for="content-title">${this.localize('content.name')}*</label>
So it shows up as `Name*` instead of just `Name`. UX thing to help users recognize it's mandatory. Assignments does this but we don't have to follow suit if we don't want.

2020-09-18 15:08 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +				timeOut.after(500),
haha agreed, this logic was copied from `assignments-detail` component. Just kept their debounce value for the title field. Assumed it was safe if we followed suit. Can make this a more legitimate variable if we feel it's necessary?

2020-09-18 15:14 UTC, ChrisKraljevicD2L commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +				<label class="d2l-label-text" for="content-title">${this.localize('content.name')}*</label>
Aaaah gotcha. Seemed a little weird with the asterix not being part of a langterm but with the explanation it makes sense :+1:

2020-09-18 15:15 UTC, ChrisKraljevicD2L commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +				timeOut.after(500),
I think making the timeout value a constant somewhere here in `activities` would be a good idea.

2020-09-18 15:31 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +					?showing="${this._titleError}">
it seems to be working properly so I assume so ... will add the `!!` to be on the extra safe side though 👍

2020-09-18 15:39 UTC, ChrisKraljevicD2L commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +					?showing="${this._titleError}">
https://travis-ci.com/github/BrightspaceHypermediaComponents/activities/jobs/387124504#L506 this isn't related to the `!!` change is it? Seems like a failing test in a seemingly unrelated component 🤔

2020-09-18 15:51 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +					?showing="${this._titleError}">
Yeah, seems completely unrelated. Re-running the tests seems to make it happy.

2020-09-18 16:14 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +				<label class="d2l-label-text" for="content-title">${this.localize('content.name')}*</label>
Yeah this is fine temporarily for now, but imo there should be something handled at the component level, like a `<d2l-label />` component that can take in a `required` property and then add anything it needs to accordingly. Whether it's adding an *, adding colour, etc.

2020-09-18 16:16 UTC, ianlaidlaw commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +		if (this._titleError) {
Lit question, if this is false, nothing gets returned here. Is that alright, or do we need to return html`` ?

2020-09-18 17:21 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +		if (this._titleError) {
It works just fine as is so I see no reason to return empty `html`.

2020-09-21 17:52 UTC, CodeBaboon commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +					maxlength="128"
Why 128? I wonder if this should be some kind of shared constant? I wonder if this should (eventually) be coming back from the hypermedia update/create action in some way?

2020-09-21 18:00 UTC, CodeBaboon submitted a review, later dismissed
I think this seems good.

2020-09-21 18:06 UTC, imcdonald-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +					maxlength="128"
This was the same value used by the `assignments-editor-detail` component. Was duplicating their logic. Totally open to other approaches if we feel this should be improved.

2020-09-22 13:01 UTC, ChrisKraljevicD2L commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +					maxlength="128"
Is there a max length for titles of units in the db? We could use that instead. I'm anticipating clients complaining that they can't have obscenely long names for units anymore.

2020-09-22 13:02 UTC, ChrisKraljevicD2L approved these changes
LGTM, the title max length comment is more of a nit.

2020-09-22 13:13 UTC, ChrisKraljevicD2L approved these changes

2020-09-22 13:23 UTC, pbrown-d2l requested changes
W should have the title length match the DB column,

2020-09-22 13:23 UTC, pbrown-d2l commented on components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
> +					maxlength="128"
It is set to 150 in the DB

`[Title] [nvarchar](150) NOT NULL,`

2020-09-22 13:24 UTC, CodeBaboon approved these changes
Sorry thought I approved with my earlier review.

2020-09-22 13:32 UTC, pbrown-d2l approved these changes

2020-09-22 13:46 UTC, merged