US122757: Use work to do filter action
BrightspaceHypermediaComponents/activities pull request #1349
Opened 2021-01-14 19:58 UTC by JasperAtD2L

https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fuserstory%2F459454738300&fdp=true?fdp=true

2021-01-14 19:58 UTC, JasperAtD2L commented on components/d2l-work-to-do/d2l-work-to-do.js
> +		const fields = [].concat(action.fields).reduce((acc, field) => {
I was hoping the siren-sdk would add default values if they weren't explicitly added. But alas it does not 👎

2021-01-15 01:04 UTC, m6jones commented on components/d2l-work-to-do/d2l-work-to-do.js
> +		if (!entity || (!entity.hasActionByName(Actions.activities.filterWorkToDo) && !entity.hasActionByName(Actions.activities.selectCustomDateRange))) {
You shouldn't need to do this? Why are you accessing the siren entity?

2021-01-15 01:05 UTC, m6jones commented on components/d2l-work-to-do/d2l-work-to-do.js
> +		const fields = [].concat(action.fields).reduce((acc, field) => {
It actually does? Not sure why you are experiencing issues. But perform siren action does add the defaults.

2021-01-15 01:05 UTC, m6jones commented on components/d2l-work-to-do/d2l-work-to-do.js
> +		const action = entity.hasActionByName(Actions.activities.filterWorkToDo)
You shouldn't be accessing the entity.

2021-01-15 01:28 UTC, m6jones requested changes
You should never access the siren entity. You are skipping the entire workflow of the siren sdk. This is pretty bad. Fix that :)

2021-01-18 13:51 UTC, JasperAtD2L commented on components/d2l-work-to-do/d2l-work-to-do.js
> +		const fields = [].concat(action.fields).reduce((acc, field) => {
Only if you don't specify a fields object: https://github.com/BrightspaceHypermediaComponents/siren-sdk/blob/master/src/es6/SirenAction.js#L110

2021-01-18 15:37 UTC, JasperAtD2L commented
> The siren sdk is designed to create a way to work with the entities without directly accessing them in the components. If you need to add new ways of working with the entities, I recommend a separate PR to siren-sdk to add that.

While the team agrees this should be done. The whole widget's data access is done via the underlying entities/collection. Changing this now would be a fairly large undertaking which we don't have the resources/time to take on. We will create a ticket to analyze and migrate to domain entities, for a dragon slayer, M2, or if we have time at the end.

2021-01-19 19:14 UTC, jcrnac commented
Given the time constraints for meeting the GA release date and the amount of work involved to refactor the code so that it is not accessing the entity directly, Luna should proceed with their current PR. 
Post GA, Maya, Rory, Luna dev, and myself will get together to discuss the work involved using using hmc-foundations rather than siren-sdk.

2021-01-19 19:16 UTC, surags submitted a review, later dismissed

2021-01-19 20:01 UTC, surags approved these changes

2021-01-19 20:06 UTC, mbardakovD2L approved these changes

2021-01-19 20:14 UTC, merged