US135527 Saving FAD dates in Activities
BrightspaceHypermediaComponents/activities pull request #2384
Opened 2022-02-14 21:37 UTC by pureooze

This PR allows FACE to submit changes to the siren entity for saving.

## Previous PR
1. https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/453
2. https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/454
3. https://github.com/BrightspaceHypermediaComponents/activities/pull/2362

## Rally Story
https://rally1.rallydev.com/#/?detail=/userstory/623042532951&fdp=true

2022-03-03 21:59 UTC, astadelbauer commented on components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
> -			defaultEndDateType,
:tada:

2022-03-04 15:02 UTC, astadelbauer approved these changes

2022-03-04 15:18 UTC, kieranderson commented on components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
> +		if (!dates.canEditAvailabilityDates) {
Duplicate. From the line above

2022-03-04 15:20 UTC, kieranderson requested changes
Duplicate check left in, otherwise 👍

2022-03-04 16:20 UTC, kieranderson approved these changes

2022-03-04 21:42 UTC, astadelbauer approved these changes

2022-03-04 21:43 UTC, merged

2022-03-04 21:45 UTC, adkulas approved these changes

2022-03-04 21:45 UTC, adkulas commented on components/d2l-activity-date-type-dialog/d2l-activity-date-type-dialog.js
> +			 * @dateType { '0': 'accessRestricted'| '1': 'submissionRestricted'| '2': 'hidden'}
Is this changed to a string because that's how we receive it from hypermedia?

2022-03-04 21:45 UTC, adkulas commented on test/d2l-activity-editor/d2l-activity-availability-dates-editor.test.js
> +			expect(endDateTypeInput).to.have.attr('text', langTerms['editor.lblVisibleWithSubmissionRestricted']);
I like it, picasso

2022-03-04 21:54 UTC, pureooze commented on components/d2l-activity-date-type-dialog/d2l-activity-date-type-dialog.js
> +			 * @dateType { '0': 'accessRestricted'| '1': 'submissionRestricted'| '2': 'hidden'}
Nah, forms convert everything to strings in events so it needs to be a string.