Fixed lang terms, unpin dependency for mfv
BrightspaceHypermediaComponents/activities pull request #2467
Opened 2022-03-14 23:40 UTC by martinwang-d2l

https://trello.com/c/1hhIIt0i/519-d2l-activity-quiz-editor-lang-terms-not-passing-latest-ci-message-format-validator

The following lang terms (the super large lang terms that were fixed during inspiration) were not passing the latest message format validator in CI:

submissionViewReleaseDateSummary
submissionViewReleaseDateSummaryBothMinMaxGrades

Fix:
- messageformat validator was fixed, fix in version 2.4.0. In the meantime, activities package for message format validator was pinned to 2.0.4. Pin removed with fix PR.
- For the plural statements, removed 'few' cases for translated lang terms, and 'one' changed to '=1', 'two' changed to '=2'.

2022-03-15 01:43 UTC, mostlyfabulous submitted a review, later dismissed

2022-03-16 03:39 UTC, bearfriend requested changes
Please take a look at https://github.com/BrightspaceHypermediaComponents/activities/pull/2469 for corrections to this.

2022-03-16 18:18 UTC, mostlyfabulous approved these changes

2022-03-16 18:24 UTC, bearfriend approved these changes

2022-03-16 18:40 UTC, mostlyfabulous commented
I think you'll need to push an empty commit to trigger CI maybe?

2022-03-16 19:45 UTC, merged